version: '3.7'

services:
  asd-terminal:
    build: 
      context: ${PWD}
      dockerfile: ${PWD}/docker/terminal/alpine.python.dockerfile
      # args:
      #   - OS_VERSION:${OS_VERSION}
      #   - DEVELOPMENT_LANG:${DEVELOPMENT_LANG}
      #   - DEVELOPMENT_VERSION:${DEVELOPMENT_VERSION}
      #   - TERMINAL_TYPE=${TERMINAL_TYPE}
    container_name: asd-terminal
    tty: true
    hostname: asd-terminal
    restart: unless-stopped
    networks:
      - caddy
    ports:
      - "7681:7681"
    labels:
      caddy: terminal.localhost
      caddy.reverse_proxy: "{{upstreams 7681}}"
      caddy.tls: internal
    volumes:
      - ${PWD}/workspace:/home/developer/workspace:rw
      - /var/run/docker.sock:/var/run/docker.sock
    # Set ttyd as the command (not entrypoint) with specified options
    command: sh -c "ttyd -p 7681 zsh"

networks:
  caddy:
    external: true
