version: "3.7"
services:
  whoami:
    image: containous/whoami
    container_name: whoami.example.com
    networks:
      - caddy
    labels:
      caddy: whoami.example.com
      caddy.reverse_proxy: "{{upstreams 80}}"
      caddy.tls: internal

networks:
  caddy:
    external: true
