version: "3.7"
services:
  whoami:
    image: containous/whoami
    container_name: asd-whoami
    networks:
      - asd_network
    labels:
      caddy: who.local
      caddy.reverse_proxy: "{{upstreams 80}}"
      caddy.tls: internal

networks:
  asd_network:
    external: true
