version: "3.7"
services:
  squid:
    # image: sameersbn/squid:3.5.27-2
    image: sameersbn/squid:3.3.8-23
    container_name: asd-proxy
    ports:
      - "3128:3128"
      # - "3129:3129"  # This port is for HTTPS
    # volumes:
    #   - ${PWD}/docker/squid/squid.conf:/etc/squid3/squid.conf
    networks:
      - caddy

networks:
  caddy:
    external: true
