version: '3.7'

services:
  asd-codeserver:
    build: 
      context: ${PWD}
      dockerfile: ${PWD}/docker/codeserver/alpine.dockerfile
      # args:
      #   - OS_VERSION:${OS_VERSION}
      #   - DEVELOPMENT_LANG:${DEVELOPMENT_LANG}
      #   - DEVELOPMENT_VERSION:${DEVELOPMENT_VERSION}
      #   - TERMINAL_TYPE=${TERMINAL_TYPE}
    container_name: asd-codeserver
    tty: true
    hostname: asd-codeserver
    restart: unless-stopped
    networks:
      - asd_network
    # dns:
    #   - asd-coredns
    # ports:
    #   - "7682:7682"
    labels:
      caddy: code.localhost
      caddy.reverse_proxy: "{{upstreams 7682}}"
      caddy.tls: internal
    volumes:
      - ${PWD}/workspace/developer:/home/developer/workspace:rw
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  asd_network:
    external: true
