version: "3.7"
services:
  privoxy:
    image: vimagick/privoxy
    container_name: asd-proxy
    ports:
      - "8118:8118"
    volumes:
      - ${PWD}/docker/privoxy/user.action:/etc/privoxy/user.action
      - ${PWD}/docker/privoxy/user.filter:/etc/privoxy/user.filter
    cap_add:
    # NET_ADMIN: This is granting privoxy the ability to configure network interfaces
    # set firewall rules, and perform other network-related administrative tasks 
    # without needing full root privileges
    # ⚠️ it does potentially introduce security risks
      - NET_ADMIN
    restart: always
    networks:
      - caddy

networks:
  caddy:
    external: true
